Repository Meghwantsingh/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#25 temperature converter
  temperature converter/index.html
  temperature converter/script.js
  temperature converter/style.css
Labels: HACKTOBERFEST-ACCEPTED

#37 added fibbonaci
  Programs- Coder/C++/Fibonacci series/fabinaccinum.cpp
Labels: Hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#38 Create TowerOfHanoi.cpp
  Programs/C++/TowerOfHanoi.cpp
Labels: Hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#51 added Maze Game Project made in JS
  Project/Web project ADD here/Maze Game/Screenshots/1.JPG
  Project/Web project ADD here/Maze Game/Screenshots/2.JPG
  Project/Web project ADD here/Maze Game/Screenshots/3.JPG
  Project/Web project ADD here/Maze Game/Screenshots/4.JPG
  Project/Web project ADD here/Maze Game/index.html
  Project/Web project ADD here/Maze Game/index.js
Labels: HACKTOBERFEST-ACCEPTED

#50 Added function to check if string is palindrome
  palindrome.py
Labels: HACKTOBERFEST-ACCEPTED

#24 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#70 Solved n even number question using recursion.
  CONTRIBUTORS.md
  RecursionPython/Even.java
Labels: HACKTOBERFEST-ACCEPTED

#43 fibonacci number fast algorithm
  Programs- Coder/C++/Fibonacci series/a.exe
  Programs- Coder/C++/Fibonacci series/fibonacci_optimised.cpp
Labels: HACKTOBERFEST-ACCEPTED
